[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@chimera/=lib/chimera/src/'
]
solc = "0.8.4"
evm_version = "istanbul"
# fail_on_revert = true